#include "common.h"

void Flow_OS(){
    printf("########################################START_OS_TEST########################################\n");
                
    RUN_TEST("1-1"    , tb_opens_shorts                              , "opens_shorts"                               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 4 ); 

    printf("########################################END_OS_TEST########################################\n");
}

void Flow_CP1(){
    printf("########################################START_CP1_TEST########################################\n");

    RUN_TEST("1-1"    , tb_opens_shorts                              , "opens_shorts"                               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 4  ); 
    RUN_TEST("1-2"    , tb_power_leakage                             , "Power_leakage"                              , Dummy       , Dummy       , "NEXT"  , "STOP"  , 5  ); 
    RUN_TEST("1-3"    , tb_input_leakage                             , "input_leakage"                              , Dummy       , Dummy       , "NEXT"  , "STOP"  , 6  ); 
    //RUN_TEST("1-9"    , tb_soc_power_reset                           , "soc_power_reset"                            , Dummy       , Dummy       , "NEXT"  , "NEXT"  , 701); 
    RUN_TEST("1-9"    , tb_soc_power_reset                           , "soc_power_reset"                            , Dummy       , Dummy       , "NEXT"  , "STOP"  , 701); 
    RUN_TEST("1-15"   , tb_read_stb_reg                              , "read_stb_reg"                               , Dummy       , Dummy       , "NEXT"  , "NEXT"  , 13 ); 
    RUN_TEST("1-13"   , tb_mbist_mux_setup                           , "mbist_mux_setup"                            , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-15"   , ReadReg_Print                             , "ReadReg_print"                               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 13 ); 
//    RUN_TEST("1-14"   , tb_write_soc_reg                             , "write_soc_reg"                              , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800);
    RUN_TEST("1-15"   , tb_read_stb_reg                              , "read_stb_reg"                               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 13 ); 
    RUN_TEST("7-2"    , tb_SOC_VREF_Monitor                          , "tb_SOC_VREF_Monitor"                        , Dummy       , Dummy       , "NEXT"  , "STOP"  , 702); 
    RUN_TEST("1-17"   , tb_flash_ip_reset                            , "flash_ip_reset"                             , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-18"   , tb_chip_enable                               , "chip_enable"                                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-19"   , tb_write_timing_reg                          , "write_timing_reg"                           , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-20"   , tb_read_timing_reg                           , "read_timing_reg"                            , Dummy       , Dummy       , "NEXT"  , "STOP"  , 14 ); 

#if 1
    //RUN_TEST("1-21"   ,tb_Write_Soc_Reg_Vref_trim                  ,"Write_Soc_Reg_Vref_trim_bin"                     ,Dummy     ,Dummy      ,"NEXT"   ,"STOP"   ,804); 
    RUN_TEST("1-21"   ,tb_Write_Soc_Reg_Vref_trim                  ,"Write_Soc_Reg_Vref_trim_bin"                     ,Dummy     ,Dummy      ,"NEXT"   ,"NEXT"   ,804); 
#endif    
    //RUN_TEST("1-20"   , tb_read_timing_reg                           , "read_timing_reg"                            , Dummy       , Dummy       , "NEXT"  , "NEXT"  , 14 ); 
    RUN_TEST("1-22"   , tb_nvr_cfg_read_cp1_id                       , "nvr_cfg_read_cp1_id_high"                   , Dummy       , Dummy       , "NEXT"  , "NEXT"  , 800); 
    RUN_TEST("1-23"   , tb_nvr_cfg_sector_erase                      , "nvr_cfg_sector_erase"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    //ReadFlash_SaveFile("NVR_CFG", AREA_NC,0X00, 0x7F,0X1);
    RUN_TEST("1-24"   , tb_nvr_cfg_read_ff                           , "nvr_cfg_read_ff_nom"                        , Dummy       , Dummy       , "NEXT"  , "STOP"  , 15 ); 
    RUN_TEST("1-26"   , tb_chip_erase_veg_trimming                   , "chip_erase_veg_trimming"                    , Dummy       , Dummy       , "NEXT"  , "STOP"  , 18 ); 
    RUN_TEST("1-27"   , tb_program_vcg_trimming                      , "program_vcg_trimming"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 19 ); 
    RUN_TEST("1-28"   , tb_program_vsl_trimming                      , "program_vsl_trimming"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 20 ); 
    RUN_TEST("1-29"   , tb_deep_program_sector_erase                 , "deep_program_sector_erase"                  , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-30"   , tb_deep_program_sector_read                  , "deep_program_sector_read"                   , Dummy,        Dummy       , "NEXT"  , "STOP"  , 21 ); 
    RUN_TEST("1-31"   , tb_deep_program_for_current_trim             , "deep_program_for_current_trim"              , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-32"   , tb_normal_read_triming                       , "normal_read_triming"                        , Dummy       , Dummy       , "NEXT"  , "NEXT"  , 22 ); 
    RUN_TEST("1-33"   , tb_m1_read_triming                           , "m1_read_triming"                            , Dummy       , Dummy       , "NEXT"  , "NEXT"  , 23 ); 
    RUN_TEST("1-34"   , tb_m0_read_triming                           , "m0_read_triming"                            , Dummy       , Dummy       , "NEXT"  , "NEXT"  , 24 ); 
    RUN_TEST("1-35"   , tb_vread_triming                             , "vread_triming"                              , Dummy       , Dummy       , "NEXT"  , "NEXT"  , 25 ); 
    RUN_TEST("1-36"   , tb_nvr_cfg_sector_erase                      , "nvr_cfg_sector_erase"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-37"   , tb_nvr_cfg_read_ff                           , "nvr_cfg_read_ff_nom_2"                      , Dummy       , Dummy       , "NEXT"  , "STOP"  , 26 ); 
    RUN_TEST("1-38"   , tb_nvr_cfg_cycling_x10                       , "nvr_cfg_cycling_x10"                        , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-39"   , tb_nvr_cfg_read_00                           , "nvr_cfg_read_00_nom"                        , Dummy       , Dummy       , "NEXT"  , "STOP"  , 27 ); 
    RUN_TEST("1-40"   , tb_nvr_cfg_sector_erase                      , "nvr_cfg_sector_erase"                       , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-41"   , tb_nvr_cfg_read_ff                           , "nvr_cfg_read_ff_nom_3"                      , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 28 ); 
    //RUN_TEST("1-42"   , tb_nvr_cfg_program_trim                      , "nvr_cfg_program_trim"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-42"   , tb_nvr_cfg_program_trim                      , "nvr_cfg_program_trim"                       , Dummy       , Dummy       , "NEXT"  , "NEXT"  , 800); 
    RUN_TEST("0-42"   , tb_nvr_cfg_program_soc_trim                  , "nvr_cfg_program_SOC_trim"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("0-43"   , tb_nvr_cfg_program_Vcode                     , "nvr_cfg_program_Vcode"                      , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    //ReadFlash_SaveFile("NVR_CFG", AREA_NC,0X00, 0x7F,0X1);
    RUN_TEST("1-43"   , tb_nvr_cfg_read_trim                         , "nvr_cfg_read_trim_nom"                      , Dummy       , Dummy       , "NEXT"  , "NEXT"  , 29 ); 
    RUN_TEST("1-44"   , tb_nvr_cfg_lock_en_sector_erase              , "nvr_cfg_lock_en_sector_erase"               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
 //   RUN_TEST("1-45"   , tb_nvr_cfg_read_trim                         , "nvr_cfg_read_trim_nom_2"                    , Dummy       , Dummy       , "NEXT"  , "STOP"  , 30 ); 
    RUN_TEST("1-45"   , tb_nvr_cfg_read_trim                         , "nvr_cfg_read_trim_nom_2"                    , Dummy       , Dummy       , "NEXT"  , "NEXT"  , 30 ); 
    RUN_TEST("1-46"   , tb_flash_ip_reset                            , "flash_ip_reset"                             , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-47"   , tb_reload_all_trim_code_CP1                  , "reload_all_trim_code_CP1"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-48"   , tb_measure_veg_chip_erase                    , "measure_veg_chip_erase"                     , Dummy       , Dummy       , "NEXT"  , "STOP"  , 31 ); 
    RUN_TEST("1-49"   , tb_measure_vcg_program                       , "measure_vcg_program"                        , Dummy       , Dummy       , "NEXT"  , "STOP"  , 32 ); 
    RUN_TEST("1-50"   , tb_measure_vsl_program                       , "measure_vsl_program"                        , Dummy       , Dummy       , "NEXT"  , "STOP"  , 33 ); 
    RUN_TEST("1-51"   , tb_mrn_me_program_00                         , "mrn_me_program_00"                          , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-52"   , tb_mrn_mo_program_00                         , "mrn_mo_program_00"                          , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-53"   , tb_clear_bist_fail_reg                       , "clear_bist_fail_reg"                        , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-54"   , tb_mrn_chip_erase                            , "mrn_chip_erase"                             , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-55"   , tb_main_read_ff                              , "main_read_ff_nom"                           , SetLevelNorm, Dummy       , "1-57"  , "NEXT"  , 34 ); 
    RUN_TEST("1-56"   , tb_main_check_error                          , "main_read_ff_nom_check"                     , Dummy       , Dummy       , "NEXT"  , "STOP"  , 34 ); 
    RUN_TEST("1-57"   , tb_rdn_read_ff                               , "rdn_read_ff_nom"                            , Dummy       , Dummy       , "NEXT"  , "STOP"  , 35 ); 
    RUN_TEST("1-58"   , tb_nvr_read_ff                               , "nvr_read_ff_nom"                            , Dummy       , Dummy       , "NEXT"  , "STOP"  , 36 ); 
    RUN_TEST("1-59"   , tb_main_read_m1_ff                           , "main_read_m1_ff_nom"                        , Dummy       , Dummy       , "1-61"  , "NEXT"  , 37 ); 
    RUN_TEST("1-60"   , tb_main_check_error                          , "main_read_m1_ff_nom_check"                  , Dummy       , Dummy       , "NEXT"  , "STOP"  , 37 ); 
    RUN_TEST("1-61"   , tb_rdn_read_m1_ff                            , "rdn_read_m1_ff_nom"                         , Dummy       , Dummy       , "NEXT"  , "STOP"  , 38 ); 
    RUN_TEST("1-62"   , tb_nvr_read_m1_ff                            , "nvr_read_m1_ff_nom"                         , Dummy       , Dummy       , "NEXT"  , "STOP"  , 39 ); 
    RUN_TEST("1-63"   , tb_mrn_gox_stress_hhi                        , "mrn_gox_stress_hhi"                         , SetLevelHigh_1P2MAX, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-69"   , tb_main_2x8rows_program_00                   , "main_2x8rows_program_00"                    , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 800); 
//    ReadFlash_SaveFile("2x8rows_", AREA_M,0X00, 0x3FFF,0X1);
    RUN_TEST("1-70"   , tb_main_2x8rows_read_m0_00                   , "main_2x8rows_read_m0_00_nom"                , Dummy       , Dummy       , "1-72"  , "NEXT"  , 45 ); 
    RUN_TEST("1-71"   , tb_main_check_error                          , "main_2x8_read_m0_00_nom_check"              , Dummy       , Dummy       , "NEXT"  , "STOP"  , 45 ); 
	RUN_TEST("1-72"   , tb_mrn_chip_erase                            , "mrn_chip_erase"                             , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-73"   , tb_main_read_m1_ff                           , "main_read_m1_ff_nom_2"                      , SetLevelNorm, Dummy       , "1-75"  , "NEXT"  , 46 ); 
    RUN_TEST("1-74"   , tb_main_check_error                          , "main_read_m1_ff_nom_check_2"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 46 ); 
    RUN_TEST("1-75"   , tb_rdn_read_m1_ff                            , "rdn_read_m1_ff_nom_2"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 47 ); 
    RUN_TEST("1-76"   , tb_nvr_read_m1_ff                            , "nvr_read_m1_ff_nom_2"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 48 ); 
    RUN_TEST("1-77"   , tb_mrn_me_1word_ff                           , "mrn_me_1word_ff"                            , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-78"   , tb_main_read_m1_ff                           , "me_main_read_m1_ff_nom"                     , Dummy       , Dummy       , "1-80"  , "NEXT"  , 49 ); 
    RUN_TEST("1-79"   , tb_main_check_error                          , "me_main_read_m1_ff_nom_check"               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 49 ); 
    RUN_TEST("1-80"   , tb_rdn_read_m1_ff                            , "me_rdn_read_m1_ff_nom"                      , Dummy       , Dummy       , "NEXT"  , "STOP"  , 50 ); 
    RUN_TEST("1-81"   , tb_nvr_read_m1_ff                            , "me_nvr_read_m1_ff_nom"                      , Dummy       , Dummy       , "NEXT"  , "STOP"  , 51 ); 
    RUN_TEST("1-82"   , tb_mrn_chip_erase                            , "mrn_chip_erase"                             , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-83"   , tb_mrn_mo_1word_ff                           , "mrn_mo_1word_ff"                            , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-84"   , tb_main_read_m1_ff                           , "mo_main_read_m1_ff_nom"                     , Dummy       , Dummy       , "1-86"  , "NEXT"  , 52 ); 
    RUN_TEST("1-85"   , tb_main_check_error                          , "mo_main_read_m1_ff_nom_check"               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 52 ); 
    RUN_TEST("1-86"   , tb_rdn_read_m1_ff                            , "mo_rdn_read_m1_ff_nom"                      , Dummy       , Dummy       , "NEXT"  , "STOP"  , 53 ); 
    RUN_TEST("1-87"   , tb_nvr_read_m1_ff                            , "mo_nvr_read_m1_ff_nom"                      , Dummy       , Dummy       , "NEXT"  , "STOP"  , 54 ); 
    RUN_TEST("1-88"   , tb_mrn_chip_erase                            , "mrn_chip_erase"                             , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-89"   , tb_main_program_diagonal                     , "main_program_diagonal"                      , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-90"   , tb_main_read_diagonal                        , "main_read_diagonal_nom"                     , Dummy       , Dummy       , "1-92"  , "NEXT"  , 55 ); 
    RUN_TEST("1-91"   , tb_main_check_error                          , "main_read_diagonal_nom_check"               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 55 ); 
    RUN_TEST("1-92"   , tb_mrn_me_program_00                         , "mrn_me_program_00"                          , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-93"   , tb_mrn_mo_program_00                         , "mrn_mo_program_00"                          , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-94"   , tb_main_sector_erase                         , "main_sector_erase"                          , SetLevelLow , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-95"   , tb_rdn_sector_erase                          , "rdn_sector_erase"                           , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-96"   , tb_nvr_sector_erase                          , "nvr_sector_erase"                           , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-97"   , tb_main_read_m1_ff                           , "main_read_m1_ff_nom_3"                      , SetLevelNorm, Dummy       , "1-99"  , "NEXT"  , 56 ); 
    RUN_TEST("1-98"   , tb_main_check_error                          , "main_read_m1_ff_nom_check_3"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 56 ); 
    RUN_TEST("1-99"   , tb_rdn_read_m1_ff                            , "rdn_read_m1_ff_nom_3"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 57 ); 
    RUN_TEST("1-100"  , tb_nvr_read_m1_ff                            , "nvr_read_m1_ff_nom_3"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 58 ); 
    RUN_TEST("1-101"  , tb_main_program_ff                           , "main_program_ff"                            , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-102"  , tb_rdn_program_ff                            , "rdn_program_ff"                             , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-103"  , tb_nvr_program_ff                            , "nvr_program_ff"                             , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-104"  , tb_main_read_m1_ff                           , "main_read_m1_ff_nom_4"                      , Dummy       , Dummy       , "1-106" , "NEXT"  , 59 ); 
    RUN_TEST("1-105"  , tb_main_check_error                          , "main_read_m1_ff_nom_check_4"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 59 ); 
    RUN_TEST("1-106"  , tb_rdn_read_m1_ff                            , "rdn_read_m1_ff_nom_4"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 60 ); 
    RUN_TEST("1-107"  , tb_nvr_read_m1_ff                            , "nvr_read_m1_ff_nom_4"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 61 ); 
    RUN_TEST("1-108"  , tb_main_program_ff                           , "main_program_ff"                            , SetLevelLow , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-109"  , tb_rdn_program_ff                            , "rdn_program_ff"                             , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-110"  , tb_nvr_program_ff                            , "nvr_program_ff"                             , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-111"  , tb_main_read_m1_ff                           , "main_read_m1_ff_nom_5"                      , SetLevelNorm, Dummy       , "1-113" , "NEXT"  , 62 ); 
    RUN_TEST("1-112"  , tb_main_check_error                          , "main_read_m1_ff_nom_check_5"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 62 ); 
    RUN_TEST("1-113"  , tb_rdn_read_m1_ff                            , "rdn_read_m1_ff_nom_5"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 63 ); 
    RUN_TEST("1-114"  , tb_nvr_read_m1_ff                            , "nvr_read_m1_ff_nom_5"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 64 ); 
    RUN_TEST("1-115"  , tb_main_program_ff                           , "main_program_ff"                            , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-116"  , tb_rdn_program_ff                            , "rdn_program_ff"                             , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-117"  , tb_nvr_program_ff                            , "nvr_program_ff"                             , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-118"  , tb_main_read_m1_ff                           , "main_read_m1_ff_nom_6"                      , SetLevelNorm, Dummy       , "1-120" , "NEXT"  , 65 ); 
    RUN_TEST("1-119"  , tb_main_check_error                          , "main_read_m1_ff_nom_check_6"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 65 ); 
    RUN_TEST("1-120"  , tb_rdn_read_m1_ff                            , "rdn_read_m1_ff_nom_6"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 66 ); 
    RUN_TEST("1-121"  , tb_nvr_read_m1_ff                            , "nvr_read_m1_ff_nom_6"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 67 ); 
    RUN_TEST("1-122"  , tb_mrn_chip_erase                            , "mrn_chip_erase"                             , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("0-1"    , tb_physical_address                          , "physical_address"                           , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-123"  , tb_main_program_ckbd                         , "main_program_ckbd"                          , SetLevelLow , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-124"  , tb_main_read_ckbd                            , "main_read_ckbd_nom"                         , SetLevelNorm, Dummy       , "1-126" , "NEXT"  , 68 ); 
    RUN_TEST("1-125"  , tb_main_check_error                          , "main_read_ckbd_nom_check"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 68 ); 
    RUN_TEST("1-126"  , tb_main_read_m0_ckbd                         , "main_read_m0_ckbd_nom"                      , Dummy       , Dummy       , "1-128" , "NEXT"  , 69 ); 
    RUN_TEST("1-127"  , tb_main_check_error                          , "main_read_m0_ckbd_nom_check"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 69 ); 
    RUN_TEST("1-128"  , tb_main_read_m1_ckbd                         , "main_read_m1_ckbd_nom"                      , Dummy       , Dummy       , "1-132" , "NEXT"  , 70 ); 
    RUN_TEST("1-129"  , tb_main_check_error                          , "main_read_m1_ckbd_nom_check"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 70 ); 
    RUN_TEST("1-132"  , tb_rdn_program_ckbd                          , "rdn_program_ckbd"                           , SetLevelLow , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-133"  , tb_rdn_read_ckbd                             , "rdn_read_ckbd_nom"                          , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 72 ); 
    RUN_TEST("1-134"  , tb_rdn_read_m0_ckbd                          , "rdn_read_m0_ckbd_nom"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 73 ); 
    RUN_TEST("1-135"  , tb_rdn_read_m1_ckbd                          , "rdn_read_m1_ckbd_nom"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 74 ); 
    RUN_TEST("1-136"  , tb_nvr_program_ckbd                          , "nvr_program_ckbd"                           , SetLevelLow , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-137"  , tb_nvr_read_ckbd                             , "nvr_read_ckbd_nom"                          , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 75 ); 
    RUN_TEST("1-138"  , tb_nvr_read_m0_ckbd                          , "nvr_read_m0_ckbd_nom"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 76 ); 
    RUN_TEST("1-139"  , tb_nvr_read_m1_ckbd                          , "nvr_read_m1_ckbd_nom"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 77 ); 
    RUN_TEST("1-140"  , tb_main_read_m0_ckbd_cg3p5v                  , "main_read_m0_ckbd_cg3p5v_nom"               , Dummy       , Dummy       , "1-142" , "NEXT"  , 78 ); 
    RUN_TEST("1-141"  , tb_main_check_error                          , "main_read_m0_ckbd_cg3p5v_check"             , Dummy       , Dummy       , "NEXT"  , "STOP"  , 78 ); 
    RUN_TEST("1-142"  , tb_rdn_read_m0_ckbd_cg3p5v                   , "rdn_read_m0_ckbd_cg3p5v_nom"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 79 ); 
    RUN_TEST("1-143"  , tb_nvr_read_m0_ckbd_cg3p5v                   , "nvr_read_m0_ckbd_cg3p5v_nom"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 80 ); 
    RUN_TEST("1-147"  , tb_mrn_cox_stress                            , "mrn_cox_stress"                             , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-148"  , tb_main_read_m0_ckbd                         , "cox_main_read_m0_ckbd_nom"                  , Dummy       , Dummy       , "1-150" , "NEXT"  , 84 ); 
    RUN_TEST("1-149"  , tb_main_check_error                          , "cox_main_read_m0_ckbd_check"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 84 ); 
    RUN_TEST("1-150"  , tb_main_read_m1_ckbd                         , "cox_main_read_m1_ckbd_nom"                  , Dummy       , Dummy       , "1-152" , "NEXT"  , 85 ); 
    RUN_TEST("1-151"  , tb_main_check_error                          , "cox_main_read_m1_ckbd_check"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 85 ); 
    RUN_TEST("1-152"  , tb_rdn_read_m0_ckbd                          , "cox_rdn_read_m0_ckbd_nom"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 86 ); 
    RUN_TEST("1-153"  , tb_rdn_read_m1_ckbd                          , "cox_rdn_read_m1_ckbd_nom"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 87 ); 
    RUN_TEST("1-154"  , tb_nvr_read_m0_ckbd                          , "cox_nvr_read_m0_ckbd_nom"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 88 ); 
    RUN_TEST("1-155"  , tb_nvr_read_m1_ckbd                          , "cox_nvr_read_m1_ckbd_nom"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 89 ); 
    RUN_TEST("1-156"  , tb_mrn_sol_ox_stress                         , "mrn_sol_ox_stress"                          , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-157"  , tb_main_read_m0_ckbd                         , "sol_main_read_m0_ckbd_nom"                  , Dummy       , Dummy       , "1-159" , "NEXT"  , 90 ); 
    RUN_TEST("1-158"  , tb_main_check_error                          , "sol_main_read_m0_ckbd_check"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 90 ); 
    RUN_TEST("1-159"  , tb_rdn_read_m0_ckbd                          , "sol_rdn_read_m0_ckbd_nom"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 91 ); 
    RUN_TEST("1-160"  , tb_nvr_read_m0_ckbd                          , "sol_nvr_read_m0_ckbd_nom"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 92 ); 
    RUN_TEST("1-161"  , tb_mrn_rdist_stress                          , "mrn_rdist_stress"                           , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-162"  , tb_main_read_m0_ckbd                         , "rdist_main_read_m0_ckbd_nom"                , SetLevelNorm, Dummy       , "1-164" , "NEXT"  , 93 ); 
    RUN_TEST("1-163"  , tb_main_check_error                          , "rdist_main_read_m0_ckbd_check"              , Dummy       , Dummy       , "NEXT"  , "STOP"  , 93 ); 
    RUN_TEST("1-164"  , tb_rdn_read_m0_ckbd                          , "rdist_rdn_read_m0_ckbd_nom"                 , Dummy       , Dummy       , "NEXT"  , "STOP"  , 94 ); 
    RUN_TEST("1-165"  , tb_nvr_read_m0_ckbd                          , "rdist_nvr_read_m0_ckbd_nom"                 , Dummy       , Dummy       , "NEXT"  , "STOP"  , 95 ); 
    RUN_TEST("1-166"  , tb_mrn_endurance_screen                      , "mrn_endurance_screen"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-167"  , tb_main_read_ff                              , "endurance_main_read_ff_nom"                 , Dummy       , Dummy       , "1-169" , "NEXT"  , 96 ); 
    RUN_TEST("1-168"  , tb_main_check_error                          , "endurance_main_read_ff_check"               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 96 ); 
    RUN_TEST("1-169"  , tb_rdn_read_ff                               , "endurance_rdn_read_ff_nom"                  , Dummy       , Dummy       , "NEXT"  , "STOP"  , 97 ); 
    RUN_TEST("1-170"  , tb_nvr_read_ff                               , "endurance_nvr_read_ff_nom"                  , Dummy       , Dummy       , "NEXT"  , "STOP"  , 98 ); 
    RUN_TEST("1-171"  , tb_main_chip_erase                           , "main_chip_erase"                            , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-172"  , tb_main_program_ckbd                         , "main_program_ckbd"                          , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-173"  , tb_main_program_ckbd                         , "main_program_ckbd"                          , SetLevelLow , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-174"  , tb_main_program_ckbd                         , "main_program_ckbd"                          , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-175"  , tb_main_read_m1_ckbd                         , "main_read_m1_ckbd_nom_2"                    , SetLevelNorm, Dummy       , "1-177" , "NEXT"  , 99 ); 
    RUN_TEST("1-176"  , tb_main_check_error                          , "main_read_m1_ckbd_nom_check_2"              , Dummy       , Dummy       , "NEXT"  , "STOP"  , 99 ); 
    RUN_TEST("1-177"  , tb_mrn_chip_erase                            , "mrn_chip_erase"                             , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-178"  , tb_main_read_m1_ff                           , "main_read_m1_ff_nom_7"                      , SetLevelNorm, Dummy       , "1-180" , "NEXT"  , 100); 
    RUN_TEST("1-179"  , tb_main_check_error                          , "main_read_m1_ff_nom_check_7"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 100); 
    RUN_TEST("1-180"  , tb_rdn_read_m1_ff                            , "rdn_read_m1_ff_nom_7"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 101); 
    RUN_TEST("1-181"  , tb_nvr_read_m1_ff                            , "nvr_read_m1_ff_nom_7"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 102); 
    RUN_TEST("1-182"  , tb_main_program_ickbd                        , "main_program_ickbd"                         , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-183"  , tb_main_read_ickbd                           , "main_read_ickbd_nom"                        , SetLevelNorm, Dummy       , "1-185" , "NEXT"  , 103); 
    RUN_TEST("1-184"  , tb_main_check_error                          , "main_read_ickbd_nom_check"                  , Dummy       , Dummy       , "NEXT"  , "STOP"  , 103); 
    RUN_TEST("1-185"  , tb_main_read_m0_ickbd                        , "main_read_m0_ickbd_nom"                     , Dummy       , Dummy       , "1-187" , "NEXT"  , 104); 
    RUN_TEST("1-186"  , tb_main_check_error                          , "main_read_m0_ickbd_nom_check"               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 104); 
    RUN_TEST("1-187"  , tb_main_read_m1_ickbd                        , "main_read_m1_ickbd_nom"                     , Dummy       , Dummy       , "1-191" , "NEXT"  , 105); 
    RUN_TEST("1-188"  , tb_main_check_error                          , "main_read_m1_ickbd_nom_check"               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 105); 
    RUN_TEST("1-191"  , tb_rdn_program_ickbd                         , "rdn_program_ickbd"                          , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-192"  , tb_rdn_read_ickbd                            , "rdn_read_ickbd_nom"                         , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 107); 
    RUN_TEST("1-193"  , tb_rdn_read_m0_ickbd                         , "rdn_read_m0_ickbd_nom"                      , Dummy       , Dummy       , "NEXT"  , "STOP"  , 108); 
    RUN_TEST("1-194"  , tb_rdn_read_m1_ickbd                         , "rdn_read_m1_ickbd_nom"                      , Dummy       , Dummy       , "NEXT"  , "STOP"  , 109); 
    RUN_TEST("1-195"  , tb_nvr_program_ickbd                         , "nvr_program_ickbd"                          , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-196"  , tb_nvr_read_ickbd                            , "nvr_read_ickbd_nom"                         , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 110); 
    RUN_TEST("1-197"  , tb_nvr_read_m0_ickbd                         , "nvr_read_m0_ickbd_nom"                      , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 111); 
    RUN_TEST("1-198"  , tb_nvr_read_m1_ickbd                         , "nvr_read_m1_ickbd_nom"                      , Dummy       , Dummy       , "NEXT"  , "STOP"  , 112); 
    RUN_TEST("1-199"  , tb_main_read_m0_ickbd_cg3p5v                 , "main_read_m0_ickbd_cg3p5v_nom"              , Dummy       , Dummy       , "1-201" , "NEXT"  , 113); 
    RUN_TEST("1-200"  , tb_main_check_error                          , "main_rd_m0_ickbd_cg3p5v_check"              , Dummy       , Dummy       , "NEXT"  , "STOP"  , 113); 
    RUN_TEST("1-201"  , tb_rdn_read_m0_ickbd_cg3p5v                  , "rdn_read_m0_ickbd_cg3p5v_nom"               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 114); 
    RUN_TEST("1-202"  , tb_nvr_read_m0_ickbd_cg3p5v                  , "nvr_read_m0_ickbd_cg3p5v_nom"               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 115); 
    RUN_TEST("1-203"  , tb_mrn_cox_stress                            , "mrn_cox_stress"                             , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-204"  , tb_main_read_m0_ickbd                        , "cox_main_read_m0_ickbd_nom"                 , Dummy       , Dummy       , "1-206" , "NEXT"  , 116); 
    RUN_TEST("1-205"  , tb_main_check_error                          , "cox_main_read_m0_ickbd_check"               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 116); 
    RUN_TEST("1-206"  , tb_main_read_m1_ickbd                        , "cox_main_read_m1_ickbd_nom"                 , Dummy       , Dummy       , "1-208" , "NEXT"  , 117); 
    RUN_TEST("1-207"  , tb_main_check_error                          , "cox_main_read_m1_ickbd_check"               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 117); 
    RUN_TEST("1-208"  , tb_rdn_read_m0_ickbd                         , "cox_rdn_read_m0_ickbd_nom"                  , Dummy       , Dummy       , "NEXT"  , "STOP"  , 118); 
    RUN_TEST("1-209"  , tb_rdn_read_m1_ickbd                         , "cox_rdn_read_m1_ickbd_nom"                  , Dummy       , Dummy       , "NEXT"  , "STOP"  , 119); 
    RUN_TEST("1-210"  , tb_nvr_read_m0_ickbd                         , "cox_nvr_read_m0_ickbd_nom"                  , Dummy       , Dummy       , "NEXT"  , "STOP"  , 120); 
    RUN_TEST("1-211"  , tb_nvr_read_m1_ickbd                         , "cox_nvr_read_m1_ickbd_nom"                  , Dummy       , Dummy       , "NEXT"  , "STOP"  , 121); 
    RUN_TEST("1-212"  , tb_mrn_sol_ox_stress                         , "sol_ox_stress"                              , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-213"  , tb_main_read_m0_ickbd                        , "sol_main_read_m0_ickbd_nom"                 , Dummy       , Dummy       , "1-215" , "NEXT"  , 122); 
    RUN_TEST("1-214"  , tb_main_check_error                          , "sol_main_read_m0_ickbd_check"               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 122); 
    RUN_TEST("1-215"  , tb_rdn_read_m0_ickbd                         , "sol_rdn_read_m0_ickbd_nom"                  , Dummy       , Dummy       , "NEXT"  , "STOP"  , 123); 
    RUN_TEST("1-216"  , tb_nvr_read_m0_ickbd                         , "sol_nvr_read_m0_ickbd_nom"                  , Dummy       , Dummy       , "NEXT"  , "STOP"  , 124); 
    RUN_TEST("1-217"  , tb_mrn_rdist_stress                          , "mrn_rdist_stress"                           , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-218"  , tb_main_read_m0_ickbd                        , "rdist_main_read_m0_ickbd_nom"               , SetLevelNorm, Dummy       , "1-220" , "NEXT"  , 125); 
    RUN_TEST("1-219"  , tb_main_check_error                          , "rdist_main_read_m0_ickbd_check"             , Dummy       , Dummy       , "NEXT"  , "STOP"  , 125); 
    RUN_TEST("1-220"  , tb_rdn_read_m0_ickbd                         , "rdist_rdn_read_m0_ickbd_nom"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 126); 
    RUN_TEST("1-221"  , tb_nvr_read_m0_ickbd                         , "rdist_nvr_read_m0_ickbd_nom"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 127); 
    RUN_TEST("1-222"  , tb_mrn_endurance_screen                      , "mrn_endurance_screen"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-223"  , tb_main_read_ff                              , "endurance_main_read_ff_nom_2"               , Dummy       , Dummy       , "1-225" , "NEXT"  , 128); 
    RUN_TEST("1-224"  , tb_main_check_error                          , "endurance_main_read_ff_check_2"             , Dummy       , Dummy       , "NEXT"  , "STOP"  , 128); 
    RUN_TEST("1-225"  , tb_rdn_read_ff                               , "endurance_rdn_read_ff_nom_2"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 129); 
    RUN_TEST("1-226"  , tb_nvr_read_ff                               , "endurance_nvr_read_ff_nom_2"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 130); 
    RUN_TEST("1-227"  , tb_main_chip_erase                           , "main_chip_erase"                            , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-228"  , tb_main_program_ickbd                        , "main_program_ickbd"                         , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-229"  , tb_main_program_ickbd                        , "main_program_ickbd"                         , SetLevelLow , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-230"  , tb_main_program_ickbd                        , "main_program_ickbd"                         , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-231"  , tb_main_read_m1_ickbd                        , "main_read_m1_ickbd_nom_2"                   , SetLevelNorm, Dummy       , "0-4"   , "NEXT"  , 131); 
    RUN_TEST("1-232"  , tb_main_check_error                          , "main_read_m1_ickbd_nom_check_2"             , Dummy       , Dummy       , "NEXT"  , "STOP"  , 131); 
    RUN_TEST("0-4"    , tb_logical_address                           , "logical_address"                            , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-233"  , tb_mrn_chip_erase                            , "mrn_chip_erase"                             , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-234"  , tb_main_read_m1_ff                           , "main_read_m1_ff_nom_8"                      , SetLevelNorm, Dummy       , "1-236" , "NEXT"  , 132); 
    RUN_TEST("1-235"  , tb_main_check_error                          , "main_read_m1_ff_nom_check_8"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 132); 
    RUN_TEST("1-236"  , tb_rdn_read_m1_ff                            , "rdn_read_m1_ff_nom_8"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 133); 
    RUN_TEST("1-237"  , tb_nvr_read_m1_ff                            , "nvr_read_m1_ff_nom_8"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 134); 
    RUN_TEST("1-238"  , tb_nvr_cfg_program_repaired_rows             , "nvr_cfg_program_repaired_rows"              , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 135); 
    RUN_TEST("1-239"  , tb_clear_bist_fail_reg                       , "clear_bist_fail_reg"                        , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-240"  , tb_flash_ip_reset                            , "flash_ip_reset"                             , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-241"  , tb_reload_all_trim_code_CP1                  , "reload_all_trim_code_CP1"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-242"  , tb_read_repair_addr                          , "read_repair_addr"                           , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-243"  , tb_mrn_chip_erase_x50                        , "mrn_chip_erase_x50"                         , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-244"  , tb_main_read_ff                              , "chip_erase_x50_main_read_ff"                , SetLevelLow , Dummy       , "1-246" , "NEXT"  , 136); 
    RUN_TEST("1-245"  , tb_main_check_sort2_error                    , "erase_x50_main_read_ff_check"               , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 136); 
    RUN_TEST("1-246"  , tb_rdn_read_ff                               , "erase_x50_rdn_read_ff_nom"                  , SetLevelLow , Dummy       , "NEXT"  , "STOP"  , 137); 
    RUN_TEST("1-247"  , tb_nvr_read_ff                               , "erase_x50_nvr_read_ff_nom"                  , Dummy       , Dummy       , "NEXT"  , "STOP"  , 138); 
    RUN_TEST("1-248"  , tb_main_1st_row_column_program_00            , "main_1st_row_column_program_00"             , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-249"  , tb_main_1st_row_column_read_00               , "main_1st_row_column_read_00"                , Dummy       , Dummy       , "1-251" , "NEXT"  , 139); 
    RUN_TEST("1-250"  , tb_main_check_sort2_error                    , "main_1st_row_read_00_check"                 , Dummy       , Dummy       , "NEXT"  , "STOP"  , 139); 
    RUN_TEST("1-250"  , tb_check_sort2_1column_error_main_array      , "main_1st_column_read_00_check"              , Dummy       , Dummy       , "NEXT"  , "STOP"  , 139);
    RUN_TEST("1-251"  , tb_mrn_chip_erase_x50                        , "mrn_chip_erase_x50"                         , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-252"  , tb_main_read_ff                              , "chip_erase_x50_main_read_ff_2"              , SetLevelLow , Dummy       , "1-254" , "NEXT"  , 140); 
    RUN_TEST("1-253"  , tb_main_check_sort2_error                    , "erase_x50_main_read_ff_check_2"             , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 140); 
    RUN_TEST("1-254"  , tb_rdn_read_ff                               , "erase_x50_rdn_read_ff_nom_2"                , SetLevelLow , Dummy       , "NEXT"  , "STOP"  , 141); 
    RUN_TEST("1-255"  , tb_nvr_read_ff                               , "erase_x50_nvr_read_ff_nom_2"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 142); 
    RUN_TEST("1-256"  , tb_main_1st_row_column_program_00            , "main_1st_row_column_program_00"             , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-257"  , tb_main_1st_row_column_read_00               , "main_1st_row_column_read_00_2"              , Dummy       , Dummy       , "1-259" , "NEXT"  , 143); 
    RUN_TEST("1-258"  , tb_main_check_sort2_error                    , "main_1st_row_read_00_check_2"               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 143); 
    RUN_TEST("1-258"  , tb_check_sort2_1column_error_main_array      , "main_1st_column_read_00_check_2"            , Dummy       , Dummy       , "NEXT"  , "STOP"  , 143);
    RUN_TEST("1-259"  , tb_mrn_chip_erase                            , "mrn_chip_erase"                             , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-260"  , tb_main_read_ff                              , "main_read_ff_low"                           , SetLevelLow , Dummy       , "1-262" , "NEXT"  , 144); 
    RUN_TEST("1-261"  , tb_main_check_sort2_error                    , "main_read_ff_low_check"                     , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 144); 
    RUN_TEST("1-262"  , tb_main_1sec_pre_program_00                  , "main_1sec_pre_program_00"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-263"  , tb_main_1sec_read_00                         , "main_1sec_read_00_nom"                      , Dummy       , Dummy       , "1-264" , "NEXT"  , 145); 
    RUN_TEST("1-263"  , tb_main_check_sort2_error                    , "main_1sec_read_00_nom_check"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 145); 
    RUN_TEST("1-264"  , tb_vread1_sector_erase_retry                 , "vread1_sector_erase_retry_nom"              , Dummy       , Dummy       , "NEXT"  , "STOP"  , 146); 
    RUN_TEST("1-265"  , tb_clear_bist_fail_reg                       , "clear_bist_fail_reg"                        , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-266"  , tb_mrn_chip_erase                            , "mrn_chip_erase"                             , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-267"  , tb_nvr_read_m1_ff                            , "nvr_read_m1_ff_nom_9"                       , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 147); 
    RUN_TEST("1-268"  , tb_main_read_m1_ff                           , "main_read_m1_ff_nom_9"                      , Dummy       , Dummy       , "1-270" , "NEXT"  , 148); 
    RUN_TEST("1-269"  , tb_main_check_sort2_error                    , "main_read_m1_ff_nom_check_9"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 148); 
    RUN_TEST("1-270"  , tb_rdn_read_m1_ff                            , "rdn_read_m1_ff_nom_9"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 149); 
    RUN_TEST("0-5"    , tb_physical_address                          , "physical_address"                           , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-271"  , tb_nvr_program_ckbd                          , "nvr_program_ckbd"                           , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-272"  , tb_main_program_ckbd                         , "main_program_ckbd"                          , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-273"  , tb_rdn_program_ckbd                          , "rdn_program_ckbd"                           , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-274"  , tb_nvr_read_m0_ckbd                          , "nvr_read_m0_ckbd_nom_3"                     , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 150); 
    RUN_TEST("1-275"  , tb_nvr_read_m1_ckbd                          , "nvr_read_m1_ckbd_nom_3"                     , Dummy       , Dummy       , "NEXT"  , "STOP"  , 151); 
    RUN_TEST("1-276"  , tb_main_read_m0_ckbd                         , "main_read_m0_ckbd_nom_3"                    , Dummy       , Dummy       , "1-278" , "NEXT"  , 152); 
    RUN_TEST("1-277"  , tb_main_check_sort2_error                    , "main_read_m0_ckbd_nom_3_check"              , Dummy       , Dummy       , "NEXT"  , "STOP"  , 152); 
    RUN_TEST("1-278"  , tb_main_read_m1_ckbd                         , "main_read_m1_ckbd_nom_3"                    , Dummy       , Dummy       , "1-280" , "NEXT"  , 153); 
    RUN_TEST("1-279"  , tb_main_check_sort2_error                    , "main_read_m1_ckbd_nom_3_check"              , Dummy       , Dummy       , "NEXT"  , "STOP"  , 153); 
    RUN_TEST("1-280"  , tb_rdn_read_m0_ckbd                          , "rdn_read_m0_ckbd_nom_3"                     , Dummy       , Dummy       , "NEXT"  , "STOP"  , 154); 
    RUN_TEST("1-281"  , tb_rdn_read_m1_ckbd                          , "rdn_read_m1_ckbd_nom_3"                     , Dummy       , Dummy       , "NEXT"  , "STOP"  , 155); 
    RUN_TEST("0-6"    , tb_logical_address                           , "logical_address"                            , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-282"  , tb_nvr_cfg_program_cp1_id                    , "nvr_cfg_program_cp1_id"                     , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("1-283"  , tb_nvr_cfg_read_cp1_id                       , "nvr_cfg_read_cp1_id_high"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 156); 
   // RUN_TEST("1-285"  ,tb_nvr_cfg_read_all_data                      ,"nvr_cfg_read_all_data"                       ,Dummy        ,Dummy        ,"NEXT"   ,"NEXT"   ,157);
    RUN_TEST("1-284"  , tb_soc_power_set_0                           , "power_set_0"                                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 

   printf("########################################END_CP1_TEST########################################\n");
}

void Flow_CP2(){
    printf("########################################START_CP2_TEST########################################\n");

    RUN_TEST("2-1"    , tb_opens_shorts                              , "opens_shorts"                               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 204); 
    RUN_TEST("2-2"    , tb_power_leakage                             , "Power_leakage"                              , Dummy       , Dummy       , "NEXT"  , "STOP"  , 205); 
    RUN_TEST("2-3"    , tb_input_leakage                             , "input_leakage"                              , Dummy       , Dummy       , "NEXT"  , "STOP"  , 206); 
    //RUN_TEST("2-9"    , tb_soc_power_reset                           , "soc_power_reset"                            , Dummy       , Dummy       , "NEXT"  , "STOP"  , 705); 
    RUN_TEST("2-9"    , tb_soc_power_reset                           , "soc_power_reset"                            , Dummy       , Dummy       , "NEXT"  , "STOP"  , 705); 
    RUN_TEST("2-15"   , tb_read_stb_reg                              , "read_stb_reg"                               , Dummy       , Dummy       , "NEXT"  , "NEXT"  , 213); 
    RUN_TEST("2-13"   , tb_mbist_mux_setup                           , "mbist_mux_setup"                            , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 800); 
//    RUN_TEST("2-14"   , tb_write_soc_reg                             , "write_soc_reg"                              , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800);
    RUN_TEST("2-15"   , tb_read_stb_reg                              , "read_stb_reg"                               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 213); 
    RUN_TEST("2-17"   , tb_flash_ip_reset                            , "flash_ip_reset"                             , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-18"   , tb_chip_enable                               , "chip_enable"                                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-19"   , tb_write_timing_reg                          , "write_timing_reg"                           , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-20"   , tb_read_timing_reg                           , "read_timing_reg"                            , Dummy       , Dummy       , "NEXT"  , "STOP"  , 214); 
    RUN_TEST("2-21"   , tb_reload_all_trim_code                      , "reload_all_trim_code"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("7-2"    , tb_SOC_VREF_Monitor                          , "tb_SOC_VREF_Monitor"                        , Dummy       , Dummy       , "NEXT"  , "STOP"  , 702); 
    //RUN_TEST("2-14"   ,tb_read_fail_addr                           ,"read_fail_addr"                                  ,Dummy     ,Dummy      ,"NEXT"   ,"NEXT"   ,800);
    RUN_TEST("2-14"   ,tb_read_repair_addr                           ,"read_pair_addr"                                  ,Dummy     ,Dummy      ,"NEXT"   ,"NEXT"   ,800);
    //RUN_TEST("2-22"   , tb_read_repair_addr                          , "read_repair_addr"                           , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-23"   , tb_nvr_cfg_read_cp2_id                       , "nvr_cfg_read_cp2_id"                        , Dummy       , Dummy       , "END"   , "NEXT"  , 800); 
    //RUN_TEST("2-23"   , tb_nvr_cfg_read_cp2_id                       , "nvr_cfg_read_cp2_id"                        , Dummy       , Dummy       , "NEXT"   , "NEXT"  , 800); 
    RUN_TEST("2-24"   , tb_nvr_cfg_read_cp1_id                       , "nvr_cfg_read_cp1_id"                        , Dummy       , Dummy       , "NEXT"  , "STOP"  , 215); 
    RUN_TEST("2-25"   , tb_nvr_cfg_read_cp2_retest_stamp             , "nvr_cfg_read_cp2_retest_stamp"              , SetLevelNorm, Dummy       , "2-35"  , "NEXT"  , 800); 
    RUN_TEST("0-1"    , tb_physical_address                          , "physical_address"                           , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-26"   , tb_nvr_read_m0_ckbd                          , "DRB_nvr_read_m0_ckbd_nom"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 216); 
    RUN_TEST("2-27"   , tb_nvr_read_m1_ht_ckbd                       , "DRB_nvr_read_m1_ht_ckbd_nom"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 217); 
    RUN_TEST("2-28"   , tb_main_read_m0_ckbd                         , "DRB_main_read_m0_ckbd_nom"                  , Dummy       , Dummy       , "2-30"  , "NEXT"  , 218); 
    RUN_TEST("2-29"   , tb_main_check_sort2_error                    , "DRB_main_read_m0_ckbd_check"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 218); 
    RUN_TEST("2-30"   , tb_main_read_m1_ht_ckbd                      , "DRB_main_read_m1_ht_ckbd_nom"               , Dummy       , Dummy       , "2-32"  , "NEXT"  , 219); 
    RUN_TEST("2-31"   , tb_main_check_sort2_error                    , "DRB_main_read_m1_ht_ckbd_check"             , Dummy       , Dummy       , "NEXT"  , "STOP"  , 219); 
    RUN_TEST("2-32"   , tb_rdn_read_m0_ckbd                          , "DRB_rdn_read_m0_ckbd_nom"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 220); 
    RUN_TEST("2-33"   , tb_rdn_read_m1_ht_ckbd                       , "DRB_rdn_read_m1_ht_ckbd_nom"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 221); 
    RUN_TEST("0-2"    , tb_logical_address                           , "logical_address"                            , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-34"   , tb_nvr_cfg_program_read_s2reteststamp        , "nvr_cfg_program_read_s2reteststamp"         , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 222); 
    RUN_TEST("2-35"   , tb_measure_veg_chip_erase_ht                 , "measure_veg_chip_erase_ht"                  , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 225); 
    RUN_TEST("2-36"   , tb_measure_vcg_program_ht                    , "measure_vcg_program_ht"                     , Dummy       , Dummy       , "NEXT"  , "STOP"  , 224); 
    RUN_TEST("2-37"   , tb_measure_vsl_program_ht                    , "measure_vsl_program_ht"                     , Dummy       , Dummy       , "NEXT"  , "STOP"  , 223); 
    RUN_TEST("2-38"   , tb_mrn_chip_erase                            , "mrn_chip_erase"                             , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-39"   , tb_main_read_m1_ht_ff                        , "main_read_m1_ht_ff_nom"                     , SetLevelNorm, Dummy       , "2-41"  , "NEXT"  , 226); 
    RUN_TEST("2-40"   , tb_main_check_sort2_error                    , "main_read_m1_ht_ff_nom_check"               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 226); 
    RUN_TEST("2-41"   , tb_rdn_read_m1_ht_ff                         , "rdn_read_m1_ht_ff_nom"                      , Dummy       , Dummy       , "NEXT"  , "STOP"  , 227); 
    RUN_TEST("2-42"   , tb_nvr_read_m1_ht_ff                         , "nvr_read_m1_ht_ff_nom"                      , Dummy       , Dummy       , "NEXT"  , "STOP"  , 228); 
    RUN_TEST("2-43"   , tb_mrn_me_1word_ff                           , "mrn_me_1word_ff"                            , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-44"   , tb_main_read_m1_ht_ff                        , "me_main_read_m1_ht_ff_nom"                  , Dummy       , Dummy       , "2-46"  , "NEXT"  , 229); 
    RUN_TEST("2-45"   , tb_main_check_sort2_error                    , "me_main_read_m1_ht_ff_check"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 229); 
    RUN_TEST("2-46"   , tb_rdn_read_m1_ht_ff                         , "me_rdn_read_m1_ht_ff_nom"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 230); 
    RUN_TEST("2-47"   , tb_nvr_read_m1_ht_ff                         , "me_nvr_read_m1_ht_ff_nom"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 231); 
    RUN_TEST("2-48"   , tb_mrn_chip_erase                            , "mrn_chip_erase"                             , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-49"   , tb_mrn_mo_1word_ff                           , "mrn_mo_1word_ff"                            , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-50"   , tb_main_read_m1_ht_ff                        , "mo_main_read_m1_ht_ff_nom"                  , Dummy       , Dummy       , "2-52"  , "NEXT"  , 232); 
    RUN_TEST("2-51"   , tb_main_check_sort2_error                    , "mo_main_read_m1_ht_ff_check"                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 232); 
    RUN_TEST("2-52"   , tb_rdn_read_m1_ht_ff                         , "mo_rdn_read_m1_ht_ff_nom"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 233); 
    RUN_TEST("2-53"   , tb_nvr_read_m1_ht_ff                         , "mo_nvr_read_m1_ht_ff_nom"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 234); 
    RUN_TEST("0-3"    , tb_physical_address                          , "physical_address"                           , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-59"   , tb_mrn_chip_erase                            , "mrn_chip_erase"                             , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-60"   , tb_nvr_program_ckbd                          , "nvr_program_ckbd"                           , SetLevelLow , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-61"   , tb_main_program_ckbd                         , "main_program_ckbd"                          , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-62"   , tb_rdn_program_ckbd                          , "rdn_program_ckbd"                           , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-63"   , tb_nvr_read_m0_ckbd                          , "nvr_read_m0_ckbd_nom"                       , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 240); 
    RUN_TEST("2-64"   , tb_nvr_read_m1_ht_ckbd                       , "nvr_read_m1_ht_ckbd_nom"                    , Dummy       , Dummy       , "NEXT"  , "STOP"  , 241); 
    RUN_TEST("2-65"   , tb_main_read_ckbd                            , "main_read_ckbd_high"                        , SetLevelHigh, Dummy       , "2-67"  , "NEXT"  , 242); 
    RUN_TEST("2-66"   , tb_main_check_sort2_error                    , "main_read_ckbd_high_check"                  , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 242); 
    RUN_TEST("2-67"   , tb_main_read_m0_ckbd                         , "main_read_m0_ckbd_nom"                      , SetLevelNorm, Dummy       , "2-69"  , "NEXT"  , 243); 
    RUN_TEST("2-68"   , tb_main_check_sort2_error                    , "main_read_m0_ckbd_check"                    , Dummy       , Dummy       , "NEXT"  , "STOP"  , 243); 
    RUN_TEST("2-69"   , tb_main_read_m1_ht_ckbd                      , "main_read_m1_ht_ckbd_nom"                   , Dummy       , Dummy       , "2-71"  , "NEXT"  , 244); 
    RUN_TEST("2-70"   , tb_main_check_sort2_error                    , "main_read_m1_ht_ckbd_check"                 , Dummy       , Dummy       , "NEXT"  , "STOP"  , 244); 
    RUN_TEST("2-71"   , tb_rdn_read_m0_ckbd                          , "rdn_read_m0_ckbd_nom"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 245); 
    RUN_TEST("2-72"   , tb_rdn_read_m1_ht_ckbd                       , "rdn_read_m1_ht_ckbd_nom"                    , Dummy       , Dummy       , "NEXT"  , "STOP"  , 246); 
    RUN_TEST("2-73"   , tb_main_sector_erase                         , "main_sector_erase"                          , SetLevelLow , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-74"   , tb_rdn_sector_erase                          , "rdn_sector_erase"                           , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-78"   , tb_nvr_sector_erase                          , "nvr_sector_erase"                           , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-75"   , tb_main_read_m1_ht_ff                        , "main_read_m1_ht_ff_nom_2"                   , SetLevelNorm, Dummy       , "2-77"  , "NEXT"  , 247); 
    RUN_TEST("2-76"   , tb_main_check_sort2_error                    , "main_read_m1_ht_ff_check_2"                 , Dummy       , Dummy       , "NEXT"  , "STOP"  , 247); 
    RUN_TEST("2-77"   , tb_rdn_read_m1_ht_ff                         , "rdn_read_m1_ht_ff_nom_2"                    , Dummy       , Dummy       , "NEXT"  , "STOP"  , 248); 
    RUN_TEST("2-79"   , tb_nvr_read_m1_ht_ff                         , "nvr_read_m1_ht_ff_nom_2"                    , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 249); 
    RUN_TEST("2-80"   , tb_nvr_program_ickbd                         , "nvr_program_ickbd"                          , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-81"   , tb_main_program_ickbd                        , "main_program_ickbd"                         , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-82"   , tb_rdn_program_ickbd                         , "rdn_program_ickbd"                          , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-83"   , tb_nvr_read_m0_ickbd                         , "nvr_read_m0_ickbd_nom"                      , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 250); 
    RUN_TEST("2-84"   , tb_nvr_read_m1_ht_ickbd                      , "nvr_read_m1_ht_ickbd_nom"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 251); 
    RUN_TEST("2-85"   , tb_main_read_m0_ickbd                        , "main_read_m0_ickbd_nom"                     , Dummy       , Dummy       , "2-87"  , "NEXT"  , 252); 
    RUN_TEST("2-86"   , tb_main_check_sort2_error                    , "main_read_m0_ickbd_nom_check"               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 252); 
    RUN_TEST("2-87"   , tb_main_read_m1_ht_ickbd                     , "main_read_m1_ht_ickbd_nom"                  , Dummy       , Dummy       , "2-89"  , "NEXT"  , 253); 
    RUN_TEST("2-88"   , tb_main_check_sort2_error                    , "main_read_m1_ht_ickbd_nom_check"            , Dummy       , Dummy       , "NEXT"  , "STOP"  , 253); 
    RUN_TEST("2-89"   , tb_rdn_read_m0_ickbd                         , "rdn_read_m0_ickbd_nom"                      , Dummy       , Dummy       , "NEXT"  , "STOP"  , 254); 
    RUN_TEST("2-90"   , tb_rdn_read_m1_ht_ickbd                      , "rdn_read_m1_ht_ickbd_nom"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 255); 
    RUN_TEST("0-4"    , tb_logical_address                           , "logical_address"                            , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-91"   , tb_nvr_cfg_program_cp2_id                    , "nvr_cfg_program_cp2_id"                     , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("2-92"   , tb_nvr_cfg_read_cp2_id                       , "nvr_cfg_read_cp2_id_high"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 256); 
    //RUN_TEST("1-285"  ,tb_nvr_cfg_read_all_data                      ,"nvr_cfg_read_all_data"                       ,Dummy        ,Dummy        ,"NEXT"   ,"NEXT"   ,157);
    RUN_TEST("2-93"   , tb_soc_power_set_0                           , "power_set_0"                                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 

    printf("########################################END_CP2_TEST########################################\n");
}

void Flow_CP3(){
    printf("########################################START_CP3_TEST########################################\n");

    RUN_TEST("3-1"    , tb_opens_shorts                              , "opens_shorts"                               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 304); 
    RUN_TEST("3-2"    , tb_power_leakage                             , "Power_leakage"                              , Dummy       , Dummy       , "NEXT"  , "STOP"  , 305); 
    RUN_TEST("3-3"    , tb_input_leakage                             , "input_leakage_low"                          , Dummy       , Dummy       , "NEXT"  , "STOP"  , 306); 
    RUN_TEST("3-9"    , tb_soc_power_reset                           , "soc_power_reset"                            , Dummy       , Dummy       , "NEXT"  , "STOP"  , 706); 
    RUN_TEST("3-13"   , tb_read_stb_reg                              , "read_stb_reg"                               , Dummy       , Dummy       , "NEXT"  , "NEXT"  , 313); 
    RUN_TEST("3-11"   , tb_mbist_mux_setup                           , "mbist_mux_setup"                            , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 800); 
    //RUN_TEST("3-12"   , tb_write_soc_reg                             , "write_soc_reg"                              , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800);
    RUN_TEST("3-13"   , tb_read_stb_reg                              , "read_stb_reg"                               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 313); 
    RUN_TEST("3-14"   , tb_flash_ip_reset                            , "flash_ip_reset"                             , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("3-15"   , tb_chip_enable                               , "chip_enable"                                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("3-16"   , tb_write_timing_reg                          , "write_timing_reg"                           , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("3-17"   , tb_read_timing_reg                           , "read_timing_reg"                            , Dummy       , Dummy       , "NEXT"  , "STOP"  , 314); 
    RUN_TEST("3-18"   , tb_reload_all_trim_code                      , "reload_all_trim_code"                       , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("7-2"    , tb_SOC_VREF_Monitor                          , "tb_SOC_VREF_Monitor"                        , Dummy       , Dummy       , "NEXT"  , "STOP"  , 702); 
    //RUN_TEST("3-14"   ,tb_read_fail_addr                           ,"read_fail_addr"                                  ,Dummy     ,Dummy      ,"NEXT"   ,"STOP"   ,310);
    RUN_TEST("3-14"   ,tb_read_repair_addr                           ,"read_repair_addr"                            ,Dummy     ,Dummy      ,"NEXT"   ,"STOP"   ,310);
    //RUN_TEST("3-19"   , tb_read_repair_addr                          , "read_repair_addr"                           , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("3-20"   , tb_nvr_cfg_read_cp3_id                       , "nvr_cfg_read_cp3_id_nom"                    , Dummy       , Dummy       , "END"   , "NEXT"  , 800); 
    //RUN_TEST("3-20"   , tb_nvr_cfg_read_cp3_id                       , "nvr_cfg_read_cp3_id_nom"                    , Dummy       , Dummy       , "NEXT"   , "NEXT"  , 800); 
    RUN_TEST("3-21"   , tb_nvr_cfg_read_cp2_id                       , "nvr_cfg_read_cp2_id_nom"                    , Dummy       , Dummy       , "NEXT"  , "STOP"  , 315); 
    RUN_TEST("3-22"   , tb_nvr_cfg_read_cp3_retest_stamp             , "nvr_cfg_read_cp3_retest_stamp"              , SetLevelNorm, Dummy       , "3-35"  , "NEXT"  , 800); 
    RUN_TEST("0-1"    , tb_physical_address                          , "physical_address"                           , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("3-23"   , tb_nvr_read_m0_ickbd                         , "DRB_nvr_read_m0_ickbd_nom"                  , Dummy       , Dummy       , "NEXT"  , "STOP"  , 316); 
    RUN_TEST("3-24"   , tb_nvr_read_m1_ht_ickbd                      , "DRB_nvr_read_m1_ht_ickbd_nom"               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 317); 
    RUN_TEST("3-25"   , tb_main_read_m0_ickbd                        , "DRB_main_read_m0_ickbd_nom"                 , Dummy       , Dummy       , "3-27"  , "NEXT"  , 318); 
    RUN_TEST("3-26"   , tb_main_check_sort2_error                    , "DRB_main_read_m0_ickbd_check"               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 318); 
    RUN_TEST("3-27"   , tb_main_read_m1_ht_ickbd                     , "DRB_main_read_m1_ht_ickbd_nom"              , Dummy       , Dummy       , "3-29"  , "NEXT"  , 319); 
    RUN_TEST("3-28"   , tb_main_check_sort2_error                    , "DRB_main_rd_m1_ht_ickbd_check"              , Dummy       , Dummy       , "NEXT"  , "STOP"  , 319); 
    RUN_TEST("3-29"   , tb_rdn_read_m0_ickbd                         , "DRB_rdn_read_m0_ickbd_nom"                  , Dummy       , Dummy       , "NEXT"  , "STOP"  , 320); 
    RUN_TEST("3-30"   , tb_rdn_read_m1_ht_ickbd                      , "DRB_rdn_read_m1_ht_ickbd_nom"               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 321); 
    RUN_TEST("0-2"    , tb_logical_address                           , "logical_address"                            , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("3-31"   , tb_nvr_cfg_program_read_s3reteststamp        , "nvr_cfg_program_read_s3reteststamp"         , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 322); 
    RUN_TEST("3-32"   , tb_main_sector_erase                         , "main_sector_erase"                          , SetLevelLow , Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("3-33"   , tb_main_read_m1_ht_ff                        , "main_read_m1_ht_ff_nom"                     , SetLevelNorm, Dummy       , "3-35"  , "NEXT"  , 323); 
    RUN_TEST("3-34"   , tb_main_check_sort2_error                    , "main_read_m1_ht_ff_nom_check"               , Dummy       , Dummy       , "NEXT"  , "STOP"  , 323); 
    RUN_TEST("3-35"   , tb_measure_veg_chip_erase_ht                 , "measure_veg_chip_erase_ht"                  , Dummy       , Dummy       , "NEXT"  , "STOP"  , 326); 
    RUN_TEST("3-36"   , tb_measure_vcg_program_ht                    , "measure_vcg_program_ht"                     , Dummy       , Dummy       , "NEXT"  , "STOP"  , 325); 
    RUN_TEST("3-37"   , tb_measure_vsl_program_ht                    , "measure_vsl_program_ht"                     , SetLevelNorm, Dummy       , "NEXT"  , "STOP"  , 324); 
    RUN_TEST("3-43"   , tb_mrn_chip_erase                            , "mrn_chip_erase"                             , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    RUN_TEST("3-45"   , tb_main_read_m1_ht_ff                        , "main_read_m1_ht_ff_nom_2"                   , SetLevelNorm, Dummy       , "3-47"  , "NEXT"  , 332); 
    RUN_TEST("3-46"   , tb_main_check_sort2_error                    , "main_read_m1_ht_ff_nom_check_2"             , Dummy       , Dummy       , "NEXT"  , "STOP"  , 332); 
    RUN_TEST("3-47"   , tb_rdn_read_m1_ht_ff                         , "rdn_read_m1_ht_ff_nom"                      , Dummy       , Dummy       , "NEXT"  , "STOP"  , 333); 
    RUN_TEST("3-44"   , tb_nvr_read_m1_ht_ff                         , "nvr_read_m1_ht_ff_nom"                      , Dummy       , Dummy       , "NEXT"  , "STOP"  , 331); 
    RUN_TEST("3-48"   , tb_nvr_cfg_program_cp3_id                    , "nvr_cfg_program_cp3_id"                     , SetLevelHigh, Dummy       , "NEXT"  , "STOP"  , 800); 
    //ReadFlash_SaveFile("NVR_CFG_CP3_", AREA_NC,0X00, 0x7F,0X1);
    RUN_TEST("3-49"   , tb_nvr_cfg_read_cp3_id                       , "nvr_cfg_read_cp3_id_high"                   , Dummy       , Dummy       , "NEXT"  , "STOP"  , 334); 
    //RUN_TEST("1-285"  ,tb_nvr_cfg_read_all_data                      ,"nvr_cfg_read_all_data"                       ,Dummy        ,Dummy        ,"NEXT"   ,"NEXT"   ,157);
    RUN_TEST("1-286"  ,tb_nvr_program_customer_data               ,"nvr_program_customer_data"                ,Dummy        ,Dummy        ,"NEXT"   ,"NEXT"   ,157);
    //ReadFlash_SaveFile("N_CUSTOM_END",AREA_N,0x00,0x23ff,0x1);
	RUN_TEST("3-50"   , tb_soc_power_set_0                           , "power_set_0"                                , Dummy       , Dummy       , "NEXT"  , "STOP"  , 800); 

    printf("########################################END_CP3_TEST########################################\n");
}

